project:
  type: book
book:
  title: mybook
  author: Norah Jones
  date: 2/20/2026
  chapters:
  - index.qmd
  - intro.qmd
  - summary.qmd
  - references.qmd
  - ftp-client.qmd
  - http-server.qmd
  - web-scraper.qmd
  - port-scanner.qmd
  - packet-sniffer.qmd
  - p2p-file-sharing.qmd
  - search-engine.qmd
  - bandwidth-monitor.qmd
  - product-landing-page.qmd
  - blog.qmd
  - portfolio-website.qmd
  - animated-navigation-toggle.qmd
  - country-lookup-using-ip-address.qmd
  - chatbot.qmd
  - slack-bot.qmd
  - twitter-bot.qmd
  - messenger-bot.qmd
  - whatsapp-butler.qmd
  - quiz-app.qmd
  - firewall.qmd
  - todo-list.qmd
  - text-editor.qmd
  - application-builder.qmd
  - drawing-app.qmd
  - survey-app.qmd
  - web-browser.qmd
  - weather-app.qmd
  - math-editor.qmd
  - music-player.qmd
  - stopwatch-app.qmd
  - url-shortener.qmd
  - payment-system.qmd
  - meme-generator.qmd
  - pomodoro-clock.qmd
  - typing-practice.qmd
  - grammar-checker.qmd
  - news-aggregator.qmd
  - calorie-counter.qmd
  - traffic-notifier.qmd
  - virtual-assistant.qmd
  - antivirus-software.qmd
  - video-call-application.qmd
  - library-management-system.qmd
  - relational-database-management-system.qmd
  - face-tracker.qmd
  - spam-classifier.qmd
  - spoiler-blocker.qmd
  - music-suggestor.qmd
  - machine-translator.qmd
  - hand-gesture-recognition.qmd
  - video-subtitle-generator.qmd
  - automatic-logo-generator.qmd
  - movie-recommendation-system.qmd
  - audio-to-sign-language-translator.qmd
  - build-an-os.qmd
  - shuffle-deck.qmd
  - sorting-visualizer.qmd
  - static-code-analyzer.qmd
  - command-line-terminal.qmd
  - uml-diagram-generator.qmd
  - pathfinding-visualizer.qmd
  - version-control-system.qmd
  - programming-language.qmd
  - codec-software.qmd
  - password-manager.qmd
  - folder-encrypter.qmd
  - password-strength-checker.qmd
  - pong.qmd
  - pong-ai.qmd
  - risk.qmd
  - chess.qmd
  - snake.qmd
  - tetris.qmd
  - chess-ai.qmd
  - snake-ai.qmd
  - map-maker.qmd
  - battleship.qmd
  - flappy-bird.qmd
  - tic-tac-toe.qmd
  - memory-puzzle.qmd
  - physics-engine.qmd
  - flappy-bird-ai.qmd
  - tic-tac-toe-ai.qmd
  - elevator-simulator.qmd
  - simulate-the-world.qmd
  - character-generator.qmd
  - game-of-life.qmd
  - deal-finder.qmd
  - expense-tracker.qmd
  - recipe-generator.qmd
  - emoji-translator.qmd
  - regex-query-tool.qmd
  - currency-converter.qmd
  - pixel-art-generator.qmd
  - directory-tree-generator.qmd
  - random-username-generator.qmd
  - roman-to-decimal-converter.qmd
  - project-euler.qmd
  - advent-of-code.qmd
  - kaggle-titanic-challenge.qmd
bibliography: references.bib
format:
  html:
    theme:
    - cosmo
    - brand
